<?php
	$item = $this->getLastestTestimonials();

?>


	<div class="testimonials clearfix">
		<div class="client-img">
		<img class="img-responsive img-thumbnail" src="<?php echo Mage::helper('testimonials')-> getImage($item)  ?>" alt="" /></div>
		<div class="clients-view">
			<p style="float:right;font-size:12px;color:#666;"><?php echo $item->getData('date'); ?></p><br/>
			<p><?php echo $item->getData('description'); ?></p>
		</div>
	</div>
	<label class="client-name"><?php echo $item->getData('name'); ?><span>|</span><a href="<?php echo $this->getUrl('')."testimonials/index/all"?>">View All</a></label>


